# Generated by Django 5.0.7 on 2024-07-24 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="authorId",
            new_name="author",
        ),
    ]
