services:
  db:
    image: mysql:8.0
    container_name: blog_api_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysql", "-h", "db", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}", "-e", "SELECT 1"]
      interval: 30s
      timeout: 10s
      retries: 5


  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: blog_api_backend
    command: sh /code/entrypoint.sh
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - celery
  
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  celery:
    build: .
    command: celery -A blogapi worker --loglevel=info
    depends_on:
      - redis
      - db
    volumes:
      - .:/code
  
  celery-beat:
    build: .
    command: celery -A blogapi beat --loglevel=info
    depends_on:
      - redis
      - db
    volumes:
      - .:/code

volumes:
  db_data:
